### ISSUE TITLE
Dynamic island modal disappeared when dragging it to different position

### ISSUE THREAD

**Issue by Trojann** [thebarbican19/BatteryBoi#14]
I had this issue in macOS 13.4.1 (22F82)

**Comment by thebarbican19** [comment]
Thanks for reporting this @Trojann, the functionality currently dismisses the window when the mouse/trackpad event is complete, i.e. when the click is released, not when it's first pressed. 

Can you please confirm again and additionally provide a screen share of this not working if possible?

**Comment by thebarbican19** [comment]
Hi @Trojann , I have just pushed a new version (2.2.2). Please check for a new update in the app and install the new version as this is resolved. Please confirm it is by letting me know otherwise or closing the issue. 

Also if you didn't see, BatteryBoi launched on [Product Hunt](https://www.producthunt.com/posts/batteryboi-open-source) today. If you haven't voted already, please do! Thanks
