### ISSUE TITLE
Battery blur

### ISSUE THREAD

**Issue by drodmantras** [thebarbican19/BatteryBoi#33]
Not sure why but after som time i get a persistant blur (which gets updated with the correct percentage) but does not go away and leaves a permanent blur.
<img width="131" alt="Screenshot 2023-09-11 at 08 02 31" src="https://github.com/thebarbican19/BatteryBoi/assets/58110607/4dd24aef-ca53-41f7-acca-55615986a6b9">

**Comment by thebarbican19** [comment]
Hi, thanks yeah this is bug that's effecting a lot of users. There will be a fix available in a few hours.

**Comment by asboy-gh** [comment]
Yeah I have this problem too. it can be easily fixed by restarting the app  From: Joe Barbour ***@***.***>Reply: thebarbican19/BatteryBoi ***@***.***>Date: September 11, 2023 at 8:44:21 PMTo: thebarbican19/BatteryBoi ***@***.***>CC: Subscribed ***@***.***>Subject:  Re: [thebarbican19/BatteryBoi] Battery blur (Issue #33)  
Hi, thanks yeah this is bug that's effecting a lot of users. There will be a fix available in a few hours.

—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you are subscribed to this thread.Message ID: ***@***.***>
[
{
***@***.***": "http://schema.org",
***@***.***": "EmailMessage",
"potentialAction": {
***@***.***": "ViewAction",
"target": "https://github.com/thebarbican19/BatteryBoi/issues/33#issuecomment-1714400855",
"url": "https://github.com/thebarbican19/BatteryBoi/issues/33#issuecomment-1714400855",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
***@***.***": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
}
]

**Comment by JasonCedric** [comment]
I have also encountered this problem. Nothing happens when I click the menu bar program icon with my mouse, and I cannot operate the blurred area with the mouse.

**Comment by JasonCedric** [comment]
<img width="446" alt="image" src="https://github.com/thebarbican19/BatteryBoi/assets/72986377/9cb54a8f-32e6-493e-b30b-af4630e7e364">

**Comment by thebarbican19** [comment]
Hi @JasonCedric, currently working on a new animation that completely fixes this. It should be out later today or tomorrow.

**Comment by thebarbican19** [comment]
Hi gang! @drodmantras, @JasonCedric, @asboy-gh & @kannicht. I am pleased to report this is now resolved as I have reworked all the animations, also BLUETOOTH IS IN!
